MooreApp.Backend/Controllers/ConsultaPreciosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MooreApp.Common.Models;
using MooreApp.Domain.Models;

namespace MooreApp.Backend.Controllers
{
    public class ConsultaPreciosController : Controller
    {
        private DataContext db = new DataContext();

        // GET: ConsultaPrecios
        public async Task<ActionResult> Index()
        {
            return View(await db.ConsultaPrecios.ToListAsync());
        }

        // GET: ConsultaPrecios/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConsultaPrecio consultaPrecio = await db.ConsultaPrecios.FindAsync(id);
            if (consultaPrecio == null)
            {
                return HttpNotFound();
            }
            return View(consultaPrecio);
        }

        // GET: ConsultaPrecios/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ConsultaPrecios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Producto,Estado,Municipio,PrecioMinimo,PrecioMaximo")] ConsultaPrecio consultaPrecio)
        {
            if (ModelState.IsValid)
            {
                db.ConsultaPrecios.Add(consultaPrecio);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(consultaPrecio);
        }

        // GET: ConsultaPrecios/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConsultaPrecio consultaPrecio = new ConsultaPrecio();
            consultaPrecio.Producto = id;
            consultaPrecio.Estado = "";
            consultaPrecio.Municipio = "";
            consultaPrecio.PrecioMinimo = 0;
            consultaPrecio.PrecioMaximo=0;


 
            if (consultaPrecio == null)
            {
                return HttpNotFound();
            }
            return View(consultaPrecio);
        }

        // POST: ConsultaPrecios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Producto,Estado,Municipio,PrecioMinimo,PrecioMaximo")] ConsultaPrecio consultaPrecio)
        {
            if (ModelState.IsValid)
            {
                db.Entry(consultaPrecio).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(consultaPrecio);
        }

        // GET: ConsultaPrecios/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ConsultaPrecio consultaPrecio = await db.ConsultaPrecios.FindAsync(id);
            if (consultaPrecio == null)
            {
                return HttpNotFound();
            }
            return View(consultaPrecio);
        }

        // POST: ConsultaPrecios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            ConsultaPrecio consultaPrecio = await db.ConsultaPrecios.FindAsync(id);
            db.ConsultaPrecios.Remove(consultaPrecio);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MooreApp.Backend/Controllers/GenericController.cs
using MooreApp.Domain.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MooreApp.Backend.Controllers
{
    public class GenericController : Controller
    {


        private DataContext db = new DataContext();


        public JsonResult GetMunicipios(string estado)
        {
         
            db.Configuration.ProxyCreationEnabled = false;
            var municipios = db.VMunicipios.Where(m => m.CODIGO_ESTADO == estado).OrderBy(o => o.CAPITAL_MCPO);
            return Json(municipios);
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

MooreApp.Backend/Controllers/V_ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MooreApp.Common.Models;
using MooreApp.Domain.Models;
using System.Globalization;

namespace MooreApp.Backend.Controllers
{
   
    public class V_ProductosController : Controller
    {
        List<Estado> estado;
        List<Municipio> municipio;
        private DataContext db = new DataContext();



        // GET: V_Productos
        public async Task<ActionResult> Index()
        {
            if (Session["IdRol"]==null)
            {
                return RedirectToAction("Login","User");
            }
            

            return View(await db.V_Productos.ToListAsync());
        }
        // GET: V_Productos/DetailPrice/RESMAC97
        public async Task<ActionResult> DetailPrice(string id)
        {
            if (Session["IdRol"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            initEstado();
            ViewBag.Estados = new SelectList(db.VEstados, "CODIGO_ESTADO", "NOMBRE_ESTADO");
            //ViewBag.Municipios = new SelectList(municipio, "CodMunicipio", "Nombre");

            var precios = await  db.PreciosStockEstadoMunicipios.Where(p => p.Producto == id).ToListAsync();
            return View(precios);
        }
        void initEstado()
        {
            estado = new List<Estado>();
            estado.Add(new Estado { CodEstado = "02", Nombre = "AMAZONAS" });
            estado.Add(new Estado { CodEstado = "03", Nombre = "ANZOATEGUI" });
            estado.Add(new Estado { CodEstado = "04", Nombre = "APURE" });
            estado.Add(new Estado { CodEstado = "05", Nombre = "ARAGUA" });
            estado.Add(new Estado { CodEstado = "06", Nombre = "BARINAS" });
            estado.Add(new Estado { CodEstado = "07", Nombre = "BOLIVAR" });
            estado.Add(new Estado { CodEstado = "08", Nombre = "CARABOBO" });
            estado.Add(new Estado { CodEstado = "09", Nombre = "COJEDES" });
            estado.Add(new Estado { CodEstado = "10", Nombre = "DELTA AMACURO" });
            estado.Add(new Estado { CodEstado = "01", Nombre = "DISTRITO CAPITAL" });
            estado.Add(new Estado { CodEstado = "11", Nombre = "FALCON" });
            estado.Add(new Estado { CodEstado = "12", Nombre = "GUARICO" });
            estado.Add(new Estado { CodEstado = "13", Nombre = "LARA" });
            estado.Add(new Estado { CodEstado = "14", Nombre = "MERIDA" });
            estado.Add(new Estado { CodEstado = "15", Nombre = "MIRANDA" });
            estado.Add(new Estado { CodEstado = "16", Nombre = "MONAGAS" });
            estado.Add(new Estado { CodEstado = "25", Nombre = "NUEVA ESPARTA" });
            estado.Add(new Estado { CodEstado = "18", Nombre = "PORTUGUESA" });
            estado.Add(new Estado { CodEstado = "19", Nombre = "SUCRE" });
            estado.Add(new Estado { CodEstado = "20", Nombre = "TACHIRA" });
            estado.Add(new Estado { CodEstado = "21", Nombre = "TRUJILLO" });
            estado.Add(new Estado { CodEstado = "24", Nombre = "VARGAS" });
            estado.Add(new Estado { CodEstado = "22", Nombre = "YARACUY" });
            estado.Add(new Estado { CodEstado = "23", Nombre = "ZULIA" });


            //PickerEstado.ItemsSource = estado.OrderBy(e => e.Nombre).ToList();
            //PickerEstado.Title = "Seleccione Estado";


        }
        void initMunicipio()
        {
            municipio = new List<Municipio>();
            //DISTRITO CAPITAL
            municipio.Add(new Municipio { CodEstado = "01", CodMunicipio = "01", Nombre = "CARACAS" });

            //02 AMAZONAS
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "01", Nombre = "LA ESMERALDA" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "02", Nombre = "SAN FERNANDO DE ATABAPO" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "03", Nombre = "PUERTO AYACUCHO" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "04", Nombre = "ISLA RATON" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "05", Nombre = "MAROA" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "06", Nombre = "SAN JUAN DE MANAPIARE" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "07", Nombre = "SAN CARLOS DE RIO NEGRO" });
            //03 ANZOATEGUI
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "01", Nombre = "ANACO" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "02", Nombre = "ARAGUA DE BARCELONA" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "03", Nombre = "PUERTO PIRITU" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "04", Nombre = "VALLE DE GUANAPE" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "05", Nombre = "PARIAGUAN" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "06", Nombre = "GUANTA" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "07", Nombre = "SOLEDAD" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "08", Nombre = "PUERTO LA CRUZ" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "09", Nombre = "ONOTO" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "10", Nombre = "MAPIRE" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "11", Nombre = "SAN MATEO" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "12", Nombre = "CLARINES" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "13", Nombre = "CANTAURA" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "14", Nombre = "PIRITU" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "15", Nombre = "SAN JOSE DE GUANIPA(El Tigrito)" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "16", Nombre = "BOCA DE UCHIRE" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "17", Nombre = "SANTA ANA" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "18", Nombre = "BARCELONA" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "19", Nombre = "El TIGRE" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "20", Nombre = "EL CHAPARRO" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "21", Nombre = "LECHERIAS" });

            //04 APURE
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "01", Nombre = "ACHAGUAS" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "02", Nombre = "BIRUACA" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "03", Nombre = "BRUZUAL" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "04", Nombre = "GUASDUALITO" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "05", Nombre = "SAN JUAN DE PAYARA" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "06", Nombre = "ELORZA" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "07", Nombre = "SAN FERNANDO DE APURE" });

            // 05 ARAGUA
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "01", Nombre = "SAN MATEO" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "02", Nombre = "CAMATAGUA" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "03", Nombre = "MARACAY" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "04", Nombre = "SANTA CRUZ" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "05", Nombre = "LA VICTORIA" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "06", Nombre = "EL CONSEJO" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "07", Nombre = "PALO NEGRO" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "08", Nombre = "EL LIMON" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "09", Nombre = "SAN CASIMIRO" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "10", Nombre = "SAN SEBASTIAN" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "11", Nombre = "TURMERO" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "12", Nombre = "LAS TEJERIAS" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "13", Nombre = "CAGUA" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "14", Nombre = "LA COLONIA TOVAR" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "15", Nombre = "BARBACOAS" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "16", Nombre = "VILLA DE CURA" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "17", Nombre = "SANTA RITA" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "18", Nombre = "OCUMARE DE LA COSTA" });

            //06 BARINAS
            municipio.Add(new Municipio { CodEstado = "06", CodMunicipio = "01", Nombre = "SABANETA" });

MooreApp.Backend/Views/V_Productos/ConsultaPrecios.cshtml
@model MooreApp.Common.Models.ConsultaPrecio

@{
    ViewBag.Title = "Consulta de Precios Stock";
}

<h2> @ViewBag.Title </h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Producto, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Producto, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Producto, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Estado", null, htmlAttributes: new { @class = "form-control" })
            @*@Html.EditorFor(model => model.Estado, new { htmlAttributes = new { @class = "form-control" } })*@
            @*@Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })*@
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Municipio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("Municipio", null, htmlAttributes: new { @class = "form-control" })
            @*@Html.EditorFor(model => model.Municipio, new { htmlAttributes = new { @class = "form-control" } })*@
            @*@Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.PrecioMinimo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            <input id="Precio" type="text" name="fname" value=@ViewBag.PrecioMinimo style="color:blue;font-size:24px;border:none">
            @*<p  style="color:blue;font-size:24px;">@ViewBag.PrecioMinimo</p>*@

        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Buscar Precio Minimo" class="btn btn-primary" />
            @Html.ActionLink("Lista Productos", "Index", new { }, new { @class = "btn btn-success" })


        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script type="text/javascript">
        var Url = '@Url.Action("GetMunicipios", "Generic")';
       
    </script>
}

MooreApp.Backend/Views/V_Productos/Create.cshtml
@model MooreApp.Common.Models.V_Productos

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>V_Productos</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PRODUCTO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PRODUCTO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PRODUCTO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DESCRIPCION, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DESCRIPCION, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DESCRIPCION, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CANTIDAD_X_CAJA, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CANTIDAD_X_CAJA, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CANTIDAD_X_CAJA, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UNIDAD_COSTEO, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UNIDAD_COSTEO, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UNIDAD_COSTEO, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MooreApp.Backend/Views/V_Productos/Delete.cshtml
@model MooreApp.Common.Models.V_Productos

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>V_Productos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DESCRIPCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DESCRIPCION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CANTIDAD_X_CAJA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CANTIDAD_X_CAJA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UNIDAD_COSTEO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UNIDAD_COSTEO)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MooreApp.Backend/Views/V_Productos/Details.cshtml
@model MooreApp.Common.Models.V_Productos

@{
    ViewBag.Title = "Details";
}

<h2>Productos Stock</h2>

<div>
    <h4>V_Productos</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DESCRIPCION)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DESCRIPCION)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CANTIDAD_X_CAJA)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CANTIDAD_X_CAJA)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UNIDAD_COSTEO)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UNIDAD_COSTEO)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PRODUCTO }) 
    @Html.ActionLink("Back to List", "Index")
</p>

MooreApp.Backend/Views/V_Productos/Index.cshtml
@model IEnumerable<MooreApp.Common.Models.V_Productos>

@{
    ViewBag.Title = "Index";
}

<style type="text/css">

    #myInput {
        background-image: url('/css/searchicon.png'); /* Add a search icon to input */
        background-position: 10px 12px; /* Position the search icon */
        background-repeat: no-repeat; /* Do not repeat the icon image */
        width: 100%; /* Full-width */
        font-size: 16px; /* Increase font-size */
        padding: 12px 20px 12px 40px; /* Add some padding */
        border: 1px solid #ddd; /* Add a grey border */
        margin-bottom: 12px; /* Add some space below the input */
    }
    #myInputDescripcion {
        background-image: url('/css/searchicon.png'); /* Add a search icon to input */
        background-position: 10px 12px; /* Position the search icon */
        background-repeat: no-repeat; /* Do not repeat the icon image */
        width: 100%; /* Full-width */
        font-size: 16px; /* Increase font-size */
        padding: 12px 20px 12px 40px; /* Add some padding */
        border: 1px solid #ddd; /* Add a grey border */
        margin-bottom: 12px; /* Add some space below the input */
    }
    
    #myTable {
        border-collapse: collapse; /* Collapse borders */
        width: 100%; /* Full-width */
        border: 1px solid #ddd; /* Add a grey border */
        font-size: 18px; /* Increase font-size */
    }

        #myTable th, #myTable td {
            text-align: left; /* Left-align text */
            padding: 12px; /* Add padding */
        }

        #myTable tr {
            /* Add a bottom border to all table rows */
            border-bottom: 1px solid #ddd;
        }

            #myTable tr.header, #myTable tr:hover {
                /* Add a grey background color to the table header and on hover */
                background-color: #f1f1f1;
            }

</style>

<h2>Productos Stock</h2>



<table id="myTable">
    <tr class="header">
        <th>
            <input type="text" id="myInput" onkeyup="myFunction()" placeholder="Buscar Por Codigo..">

            <!--@Html.DisplayNameFor(model => model.PRODUCTO)-->
        </th>
        <th>
            <input type="text" id="myInputDescripcion" onkeyup="myFunctionDescripcion()" placeholder="Buscar Por Descripcion..">

            <!--@Html.DisplayNameFor(model => model.DESCRIPCION)-->
        </th>

            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.PRODUCTO)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DESCRIPCION)
                </td>

                <td>
                   
                    @Html.ActionLink("Precios","ConsultaPrecios", new { id = item.PRODUCTO }) 
                   
                </td>
            </tr>
        }

    </table>
    <script>
        function myFunction() {
            // Declare variables
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInput");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[0];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
        function myFunctionDescripcion() {
            // Declare variables
            var input, filter, table, tr, td, i, txtValue;
            input = document.getElementById("myInputDescripcion");
            filter = input.value.toUpperCase();
            table = document.getElementById("myTable");
            tr = table.getElementsByTagName("tr");

            // Loop through all table rows, and hide those who don't match the search query
            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[1];
                if (td) {
                    txtValue = td.textContent || td.innerText;
                    if (txtValue.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>