MooreApp.Backend/Controllers/V_ProductosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MooreApp.Common.Models;
using MooreApp.Domain.Models;
using System.Globalization;

namespace MooreApp.Backend.Controllers
{
   
    public class V_ProductosController : Controller
    {
        List<Estado> estado;
        List<Municipio> municipio;
        private DataContext db = new DataContext();



        // GET: V_Productos
        public async Task<ActionResult> Index()
        {
            if (Session["IdRol"]==null)
            {
                return RedirectToAction("Login","User");
            }
            

            return View(await db.V_Productos.ToListAsync());
        }
        // GET: V_Productos/DetailPrice/RESMAC97
        public async Task<ActionResult> DetailPrice(string id)
        {
            if (Session["IdRol"] == null)
            {
                return RedirectToAction("Login", "User");
            }
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            initEstado();
            ViewBag.Estados = new SelectList(db.VEstados, "CODIGO_ESTADO", "NOMBRE_ESTADO");
            //ViewBag.Municipios = new SelectList(municipio, "CodMunicipio", "Nombre");

            var precios = await  db.PreciosStockEstadoMunicipios.Where(p => p.Producto == id).ToListAsync();
            return View(precios);
        }
        void initEstado()
        {
            estado = new List<Estado>();
            estado.Add(new Estado { CodEstado = "02", Nombre = "AMAZONAS" });
            estado.Add(new Estado { CodEstado = "03", Nombre = "ANZOATEGUI" });
            estado.Add(new Estado { CodEstado = "04", Nombre = "APURE" });
            estado.Add(new Estado { CodEstado = "05", Nombre = "ARAGUA" });
            estado.Add(new Estado { CodEstado = "06", Nombre = "BARINAS" });
            estado.Add(new Estado { CodEstado = "07", Nombre = "BOLIVAR" });
            estado.Add(new Estado { CodEstado = "08", Nombre = "CARABOBO" });
            estado.Add(new Estado { CodEstado = "09", Nombre = "COJEDES" });
            estado.Add(new Estado { CodEstado = "10", Nombre = "DELTA AMACURO" });
            estado.Add(new Estado { CodEstado = "01", Nombre = "DISTRITO CAPITAL" });
            estado.Add(new Estado { CodEstado = "11", Nombre = "FALCON" });
            estado.Add(new Estado { CodEstado = "12", Nombre = "GUARICO" });
            estado.Add(new Estado { CodEstado = "13", Nombre = "LARA" });
            estado.Add(new Estado { CodEstado = "14", Nombre = "MERIDA" });
            estado.Add(new Estado { CodEstado = "15", Nombre = "MIRANDA" });
            estado.Add(new Estado { CodEstado = "16", Nombre = "MONAGAS" });
            estado.Add(new Estado { CodEstado = "25", Nombre = "NUEVA ESPARTA" });
            estado.Add(new Estado { CodEstado = "18", Nombre = "PORTUGUESA" });
            estado.Add(new Estado { CodEstado = "19", Nombre = "SUCRE" });
            estado.Add(new Estado { CodEstado = "20", Nombre = "TACHIRA" });
            estado.Add(new Estado { CodEstado = "21", Nombre = "TRUJILLO" });
            estado.Add(new Estado { CodEstado = "24", Nombre = "VARGAS" });
            estado.Add(new Estado { CodEstado = "22", Nombre = "YARACUY" });
            estado.Add(new Estado { CodEstado = "23", Nombre = "ZULIA" });


            //PickerEstado.ItemsSource = estado.OrderBy(e => e.Nombre).ToList();
            //PickerEstado.Title = "Seleccione Estado";


        }
        void initMunicipio()
        {
            municipio = new List<Municipio>();
            //DISTRITO CAPITAL
            municipio.Add(new Municipio { CodEstado = "01", CodMunicipio = "01", Nombre = "CARACAS" });

            //02 AMAZONAS
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "01", Nombre = "LA ESMERALDA" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "02", Nombre = "SAN FERNANDO DE ATABAPO" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "03", Nombre = "PUERTO AYACUCHO" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "04", Nombre = "ISLA RATON" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "05", Nombre = "MAROA" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "06", Nombre = "SAN JUAN DE MANAPIARE" });
            municipio.Add(new Municipio { CodEstado = "02", CodMunicipio = "07", Nombre = "SAN CARLOS DE RIO NEGRO" });
            //03 ANZOATEGUI
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "01", Nombre = "ANACO" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "02", Nombre = "ARAGUA DE BARCELONA" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "03", Nombre = "PUERTO PIRITU" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "04", Nombre = "VALLE DE GUANAPE" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "05", Nombre = "PARIAGUAN" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "06", Nombre = "GUANTA" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "07", Nombre = "SOLEDAD" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "08", Nombre = "PUERTO LA CRUZ" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "09", Nombre = "ONOTO" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "10", Nombre = "MAPIRE" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "11", Nombre = "SAN MATEO" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "12", Nombre = "CLARINES" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "13", Nombre = "CANTAURA" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "14", Nombre = "PIRITU" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "15", Nombre = "SAN JOSE DE GUANIPA(El Tigrito)" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "16", Nombre = "BOCA DE UCHIRE" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "17", Nombre = "SANTA ANA" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "18", Nombre = "BARCELONA" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "19", Nombre = "El TIGRE" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "20", Nombre = "EL CHAPARRO" });
            municipio.Add(new Municipio { CodEstado = "03", CodMunicipio = "21", Nombre = "LECHERIAS" });

            //04 APURE
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "01", Nombre = "ACHAGUAS" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "02", Nombre = "BIRUACA" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "03", Nombre = "BRUZUAL" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "04", Nombre = "GUASDUALITO" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "05", Nombre = "SAN JUAN DE PAYARA" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "06", Nombre = "ELORZA" });
            municipio.Add(new Municipio { CodEstado = "04", CodMunicipio = "07", Nombre = "SAN FERNANDO DE APURE" });

            // 05 ARAGUA
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "01", Nombre = "SAN MATEO" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "02", Nombre = "CAMATAGUA" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "03", Nombre = "MARACAY" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "04", Nombre = "SANTA CRUZ" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "05", Nombre = "LA VICTORIA" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "06", Nombre = "EL CONSEJO" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "07", Nombre = "PALO NEGRO" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "08", Nombre = "EL LIMON" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "09", Nombre = "SAN CASIMIRO" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "10", Nombre = "SAN SEBASTIAN" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "11", Nombre = "TURMERO" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "12", Nombre = "LAS TEJERIAS" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "13", Nombre = "CAGUA" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "14", Nombre = "LA COLONIA TOVAR" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "15", Nombre = "BARBACOAS" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "16", Nombre = "VILLA DE CURA" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "17", Nombre = "SANTA RITA" });
            municipio.Add(new Municipio { CodEstado = "05", CodMunicipio = "18", Nombre = "OCUMARE DE LA COSTA" });

            //06 BARINAS
            municipio.Add(new Municipio { CodEstado = "06", CodMunicipio = "01", Nombre = "SABANETA" });

MooreApp.Backend/Controllers/WSMY501Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MooreApp.Common.Models;
using MooreApp.Domain.Models;

namespace MooreApp.Backend.Controllers
{
    public class WSMY501Controller : Controller
    {
        private DataContext db = new DataContext();

        // GET: WSMY501
        public async Task<ActionResult> Index()
        {
            return View(await db.WSMY501.Where(w => w.Fecha.Value.Year == 2020).ToListAsync());
        }

        // GET: WSMY501/Details/5
        public async Task<ActionResult> Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WSMY501 wSMY501 = await db.WSMY501.FindAsync(id);
            if (wSMY501 == null)
            {
                return HttpNotFound();
            }
            return View(wSMY501);
        }

        // GET: WSMY501/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: WSMY501/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Cotizacion,Cod_Vendedor,Cod_Cliente,Prospecto,Fecha,Observaciones,Fecha_Caducidad,Fecha_Postergada,Estatus,Razon_Social,Tipo,Sector,Ramo,Email_Cliente,Rif,Condicion,Id_Contacto,Observacion_Postergar,Fecha_EnEspera,Fecha_Cerrada,UsuarioActualiza,FechaActualiza,NombreContacto,TelefonoContacto,EmailContacto,Id_direccion,DireccionFacturar,DireccionEntregar,FlagWebSite,RifEntregar,OrdenCompra,IdMedio,FlagActualizado,Id_direccionEntregar,EstadoFacturar,MunicipioFacturar,EstadoEntregar,MunicipioEntregar,FlagValidado,FechaReactivacion,IdClienteProspecto,idsolicitudCredito,UltimoEvaluadorCredito,EvaluadaAdministradora,CambioPrecio,Noreplicar,IdTipoTransaccion,NegocioEnUsd,FijarPrecioBs,FijarPrecioBsAprobado,FechaPago,ObservacionPago")] WSMY501 wSMY501)
        {
            if (ModelState.IsValid)
            {
                db.WSMY501.Add(wSMY501);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(wSMY501);
        }

        // GET: WSMY501/Edit/5
        public async Task<ActionResult> Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WSMY501 wSMY501 = await db.WSMY501.FindAsync(id);
            if (wSMY501 == null)
            {
                return HttpNotFound();
            }
            return View(wSMY501);
        }

        // POST: WSMY501/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Cotizacion,Cod_Vendedor,Cod_Cliente,Prospecto,Fecha,Observaciones,Fecha_Caducidad,Fecha_Postergada,Estatus,Razon_Social,Tipo,Sector,Ramo,Email_Cliente,Rif,Condicion,Id_Contacto,Observacion_Postergar,Fecha_EnEspera,Fecha_Cerrada,UsuarioActualiza,FechaActualiza,NombreContacto,TelefonoContacto,EmailContacto,Id_direccion,DireccionFacturar,DireccionEntregar,FlagWebSite,RifEntregar,OrdenCompra,IdMedio,FlagActualizado,Id_direccionEntregar,EstadoFacturar,MunicipioFacturar,EstadoEntregar,MunicipioEntregar,FlagValidado,FechaReactivacion,IdClienteProspecto,idsolicitudCredito,UltimoEvaluadorCredito,EvaluadaAdministradora,CambioPrecio,Noreplicar,IdTipoTransaccion,NegocioEnUsd,FijarPrecioBs,FijarPrecioBsAprobado,FechaPago,ObservacionPago")] WSMY501 wSMY501)
        {
            if (ModelState.IsValid)
            {
                db.Entry(wSMY501).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(wSMY501);
        }

        // GET: WSMY501/Delete/5
        public async Task<ActionResult> Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            WSMY501 wSMY501 = await db.WSMY501.FindAsync(id);
            if (wSMY501 == null)
            {
                return HttpNotFound();
            }
            return View(wSMY501);
        }

        // POST: WSMY501/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(string id)
        {
            WSMY501 wSMY501 = await db.WSMY501.FindAsync(id);
            db.WSMY501.Remove(wSMY501);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MooreApp.Backend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title </title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MooreApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>

                    <li>@Html.ActionLink("Productos", "Index", "V_Productos")</li>

                    <li>@Html.ActionLink("Backlog Inicial", "Index", "AppBacklogInicials")</li>
                    <li>@Html.ActionLink("Cotizaciones", "Index", "WSMY501")</li>



                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    @*<div class="container body-content" margin-left: 10px;>*@
        <div class="container" margin-left: 10px;  >
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Moore de Venezuela</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
</body>
</html>

MooreApp.Backend/Views/Shared/_LayoutAnonimo.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width initial-scale=1.0 maximum-scale=1.0 user-scalable=yes" />
    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/Scripts/Util.js")
    @Styles.Render("~/Content/Menu.css")
    @Styles.Render("~/Content/jquery.mmenu.all.css")
    @Styles.Render("~/Content/bootstrap.min.css")
    @Styles.Render("~/Content/dataTables.bootstrap.css")
    @Styles.Render("~/Content/dataTables.responsive.css")
    @Styles.Render("~/Content/jquery.dataTables.min.css")
    @Styles.Render("~/Content/dataTables.tableTools.css")
    @Styles.Render("~/Content/dataTables.editor.min.css")
    @Styles.Render("~/Content/themes/jsTree/default/style.min.css")
    @Styles.Render("~/Content/font-awesome.min.css")
    @Styles.Render("~/Content/bootstrap-datetimepicker.min.css")
    @Scripts.Render("~/Scripts/bootstrap-datetimepicker.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datepicker.es.js")

    <link rel="stylesheet" href="~/Content/themes/jsTree/default/style.min.css" />
    <script src="~/Scripts/jstree.min.js"></script>    
    <script src='https://www.google.com/recaptcha/api.js'></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>   

    @RenderBody()

    @Scripts.Render("~/Scripts/jquery.mmenu.min.all.js")
    @Scripts.Render("~/Scripts/bootstrap.min.js")
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    @Scripts.Render("~/Scripts/dataTables.tableTools.min.js")    
    @Scripts.Render("~/Scripts/numeral.min.js")    
    @Scripts.Render("~/Scripts/dataTables.bootstrap.js")
    @Scripts.Render("~/Scripts/dataTables.responsive.min.js")
    @Scripts.Render("~/Scripts/bootstrap-filestyle.js")
    @Scripts.Render("~/Scripts/jstree.min.js")    
    @Scripts.Render("~/Scripts/ContadorCaracteres.js")
    @RenderSection("scripts", required: false)
    
    <script type="text/javascript">

        function filterGlobal() {
            $('#classesTable').DataTable().search(
                $('#global_filter').val()
            ).draw();
        }

        function filterColumn(i) {
            $('#classesTable').DataTable().column(i).search(
                $('#col' + i + '_filter').val()
            ).draw();
        }

        $(document).ready(function () {           
                      
            $('#classesTable').dataTable({
                responsive: true,
                aLengthMenu: [
                    [50, 100, 500, -1],
                    [50, 100, 500, "Todos"]
                ],
                language: {
                    sProcessing: "Procesando...",
                    sLengthMenu: "Mostrar _MENU_ registros",
                    sZeroRecords: "No se encontraron resultados",
                    sEmptyTable: "Ningún dato disponible en esta tabla",
                    sInfo: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    sInfoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                    sInfoFiltered: "(filtrado de un total de _MAX_ registros)",
                    sInfoPostFix: "",
                    sSearch: "Buscar:",
                    sUrl: "",
                    sInfoThousands: ",",
                    sLoadingRecords: "Cargando...",
                    oPaginate: {
                        sFirst: "Primero",
                        sLast: "Último",
                        sNext: "Siguiente",
                        sPrevious: "Anterior "
                    },
                    oAria: {
                        SortAscending: ": Activar para ordenar la columna de manera ascendente",
                        SortDescending: ": Activar para ordenar la columna de manera descendente"
                    }
                },
                order: [[0, 'asc']]
            });

            $('#TablaSolicitud').dataTable({
                dom: '<"clear">',
                aLengthMenu: [
                            [10, 25, 100, -1],
                            [10, 25, 100, "Todos"]
                ],
                language: {
                    sProcessing: "Procesando...",
                    sLengthMenu: "Mostrar _MENU_ registros",
                    sZeroRecords: "No se encontraron resultados",
                    sEmptyTable: "Ningún dato disponible en esta tabla",
                    sInfo: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    sInfoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                    sInfoFiltered: "(filtrado de un total de _MAX_ registros)",
                    sInfoPostFix: "",
                    sSearch: "Buscar: ",
                    sUrl: "",
                    sInfoThousands: ",",
                    sLoadingRecords: "Cargando...",
                    oPaginate: {
                        sFirst: "Primero",
                        sLast: "Último",
                        sNext: "Siguiente",
                        sPrevious: "Anterior"
                    },
                    oAria: {
                        SortAscending: ": Activar para ordenar la columna de manera ascendente",
                        SortDescending: ": Activar para ordenar la columna de manera descendente"
                    }
                },
                order: [[0, 'asc']]
            });

            
            $('#TablaTest').dataTable({
                aLengthMenu: [
                            [200, 300, 500, -1],
                            [200, 300, 500, "Todos"]
                ],
                language: {
                    sProcessing: "Procesando...",
                    sLengthMenu: "Mostrar _MENU_ registros",
                    sZeroRecords: "No se encontraron resultados",
                    sEmptyTable: "Ningún dato disponible en esta tabla",
                    sInfo: "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                    sInfoEmpty: "Mostrando registros del 0 al 0 de un total de 0 registros",
                    sInfoFiltered: "(filtrado de un total de _MAX_ registros)",
                    sInfoPostFix: "",
                    sSearch: "Buscar: ",
                    sUrl: "",
                    sInfoThousands: ",",
                    sLoadingRecords: "Cargando...",
                    oPaginate: {
                        sFirst: "Primero",
                        sLast: "Último",
                        sNext: "Siguiente",
                        sPrevious: "Anterior"
                    },
                    oAria: {
                        SortAscending: ": Activar para ordenar la columna de manera ascendente",
                        SortDescending: ": Activar para ordenar la columna de manera descendente"
                    }
                },
                order: [[0, 'asc']]
            });
            

            $('input.global_filter').on('keyup click', function () {
                filterGlobal();
            });

            $('input.column_filter').on('keyup click', function () {
                filterColumn($(this).parents('th').attr('data-column'));
            });

            window.setTimeout(function () {
                $(".alert").fadeTo(4000, 0).slideUp(500, function () {
                    $(this).remove();
                });
            }, 6000);
        });

    </script>

</body>
</html>